/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.bp2project1;

import static com.fsm.bp2project1.AliEnesGurelData.kullaniciListesi;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alien
 */
public class AliEnesGurelRegister extends javax.swing.JFrame {

    JFrame loginFrame;

    /**
     * Creates new form Register
     */
    public AliEnesGurelRegister(JFrame loginFrame) {
        setTitle("KAYIT EKRANI");
        initComponents();
        this.loginFrame = loginFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kullaniciadi = new javax.swing.JTextField();
        ptxt_sifre = new javax.swing.JPasswordField();
        btn_kayit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(448, 293));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(448, 293));
        jPanel1.setMinimumSize(new java.awt.Dimension(448, 293));
        jPanel1.setPreferredSize(new java.awt.Dimension(448, 293));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("KAYIT OL");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KULLANICI ADI");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ŞİFRE");

        btn_kayit.setText("Kayıt Ol");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("E-MAIL");

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ptxt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_kullaniciadi, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(txt_email)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ptxt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_kayit)
                .addGap(54, 54, 54))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed
        AliEnesGurelKullanici newk = new AliEnesGurelKullanici();
        newk.email = txt_email.getText();
        newk.kullanici_Adi = txt_kullaniciadi.getText();
        newk.parola = new String(ptxt_sifre.getPassword());
        if (kayit_icin_uygunMu() == true) {
            try {
                AliEnesGurelData.AddKullanici(newk);
                this.loginFrame.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
            try {
                AliEnesGurelData.DosyayaKullaniciYazdirma();
            } catch (IOException ex) {
                Logger.getLogger(AliEnesGurelRegister.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_kayitActionPerformed

    public boolean kayit_icin_uygunMu() {
        AliEnesGurelKullanici newk = new AliEnesGurelKullanici();
        newk.email = txt_email.getText();
        newk.kullanici_Adi = txt_kullaniciadi.getText();
        newk.parola = new String(ptxt_sifre.getPassword());

        try {
            if (!newk.email.matches("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\\d]{6,}@(othello)\\.com$")) {
                throw new Exception("Lütfen geçerli bir e-mail adresi giriniz!\nE-mail adresiniz en az 6 karakter uzunlugunda olmalidir!\nEn az bir tane rakam ve buyuk kucuk harf icermelidir!\nYalnizca @othello.com ile giris yapabilirsiniz!\nornek: Example123@othello.com");
            }
            if (txt_email.getText().isEmpty()) {
                throw new Exception("Lütfen email adresinizi giriniz!");
            }
            if (!newk.kullanici_Adi.matches("^[a-zA-Z]{3,12}$")) {
                throw new Exception("Lütfen geçerli bir kullanici adi giriniz!\nKullanici adiniz en az 3 en fazla 12 karakter olabilir!\nBuyuk ve kucuk harf kullanmalisiniz!\nOrnek: Example");
            }
            if (txt_kullaniciadi.getText().isEmpty()) {
                throw new Exception("Lütfen kullanıcı adınızı giriniz!");
            }
            if (ptxt_sifre.getPassword().length < 4) {
                throw new Exception("Lütfen şifrenizin uzunluğu en az 4 karakter olacak şekilde giriniz!");
            }
            for (AliEnesGurelKullanici k : kullaniciListesi) {
                if (k.kullanici_Adi.compareTo(newk.kullanici_Adi) == 0) {
                    throw new Exception("Boyle bir kullanici zaten mevcut");
                }
            }
            AliEnesGurelKullanici k1 = new AliEnesGurelKullanici();
            k1.parola = new String(ptxt_sifre.getPassword());
            String rpassword = JOptionPane.showInputDialog(rootPane, "Lütfen parolanızı tekrar giriniz.", JOptionPane.INFORMATION_MESSAGE);
            if (k1.parola.equals(rpassword)) {
                return true;
            } else if (!k1.parola.equals(rpassword)) {
                throw new Exception("Parolanız önceki ile eşleşmiyor.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kayit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField ptxt_sifre;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_kullaniciadi;
    // End of variables declaration//GEN-END:variables
}
