/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.bp2project1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alien
 */
public class AliEnesGurelLogin extends javax.swing.JFrame {

    private static AliEnesGurelKullanici kullanici1 = new AliEnesGurelKullanici();
    private static AliEnesGurelKullanici kullanici2 = new AliEnesGurelKullanici();
    private static AliEnesGurelKullanici berabere = new AliEnesGurelKullanici();
    public static ArrayList<AliEnesGurelKullanici> kullanici_listesi = new ArrayList<AliEnesGurelKullanici>();

    public static ArrayList<AliEnesGurelKullanici> getKullanici_listesi() {
        return kullanici_listesi;
    }

    public static void setKullanici_listesi(ArrayList<AliEnesGurelKullanici> kullanici_list) {
        AliEnesGurelLogin.kullanici_listesi = kullanici_listesi;
    }

    public AliEnesGurelKullanici getKullanici1() {
        return kullanici1;
    }

    public void setKullanici1(AliEnesGurelKullanici kullanici1) {
        this.kullanici1 = kullanici1;
    }

    public AliEnesGurelKullanici getKullanici2() {
        return kullanici2;
    }

    public void setKullanici2(AliEnesGurelKullanici kullanici2) {
        this.kullanici2 = kullanici2;
    }

    public static AliEnesGurelKullanici getBerabere() {
        return berabere;
    }

    public static void setBerabere(AliEnesGurelKullanici berabere) {
        AliEnesGurelLogin.berabere = berabere;
    }

    /**
     * Creates new form Login
     */
    public AliEnesGurelLogin() {
        setTitle("GIRIS EKRANI");
        initComponents();
        berabere.email = "OYUN";
        berabere.kullanici_Adi = "BERABERE";
        berabere.parola = "SKORLAR: ";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_kullanici_adi1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_hazir1 = new javax.swing.JButton();
        btn_kayit_ol1 = new javax.swing.JButton();
        ptxt_sifre1 = new javax.swing.JPasswordField();
        chcbx_sifregoster1 = new javax.swing.JCheckBox();
        lbl_siyahBekleniyor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_email1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kullanici_adi2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_hazir2 = new javax.swing.JButton();
        btn_kayit_ol2 = new javax.swing.JButton();
        ptxt_sifre2 = new javax.swing.JPasswordField();
        chcbx_sifregoster2 = new javax.swing.JCheckBox();
        lbl_beyazBekleniyor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_email2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 25));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("OTURUM AÇ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(333, 333, 333))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(400, 475));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 475));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SİYAH OYUNCU");

        txt_kullanici_adi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kullanici_adi1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KULLANICI ADI");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ŞİFRE");

        btn_hazir1.setText("HAZIR");
        btn_hazir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hazir1ActionPerformed(evt);
            }
        });

        btn_kayit_ol1.setText("KAYIT OL");
        btn_kayit_ol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayit_ol1ActionPerformed(evt);
            }
        });

        chcbx_sifregoster1.setBackground(new java.awt.Color(0, 0, 0));
        chcbx_sifregoster1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        chcbx_sifregoster1.setForeground(new java.awt.Color(255, 255, 255));
        chcbx_sifregoster1.setText("Şifreyi Göster");
        chcbx_sifregoster1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcbx_sifregoster1ActionPerformed(evt);
            }
        });

        lbl_siyahBekleniyor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_siyahBekleniyor.setText("BEKLENİYOR...");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SIYAH OYUNCU");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-MAIL");

        txt_email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_hazir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kayit_ol1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_siyahBekleniyor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kullanici_adi1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chcbx_sifregoster1)
                                    .addComponent(ptxt_sifre1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_kullanici_adi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ptxt_sifre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chcbx_sifregoster1)
                .addGap(30, 30, 30)
                .addComponent(btn_hazir1)
                .addGap(18, 18, 18)
                .addComponent(btn_kayit_ol1)
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_siyahBekleniyor)
                    .addComponent(jLabel9))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(400, 475));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 475));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 475));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BEYAZ OYUNCU");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("KULLANICI ADI");

        txt_kullanici_adi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kullanici_adi2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ŞİFRE");

        btn_hazir2.setText("HAZIR");
        btn_hazir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hazir2ActionPerformed(evt);
            }
        });

        btn_kayit_ol2.setText("KAYIT OL");
        btn_kayit_ol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayit_ol2ActionPerformed(evt);
            }
        });

        chcbx_sifregoster2.setBackground(new java.awt.Color(255, 255, 255));
        chcbx_sifregoster2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        chcbx_sifregoster2.setForeground(new java.awt.Color(0, 0, 0));
        chcbx_sifregoster2.setText("Şifreyi Göster");
        chcbx_sifregoster2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcbx_sifregoster2ActionPerformed(evt);
            }
        });

        lbl_beyazBekleniyor.setForeground(new java.awt.Color(0, 0, 0));
        lbl_beyazBekleniyor.setText("BEKLENİYOR...");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("BEYAZ OYUNCU");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("E-MAIL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(chcbx_sifregoster2)
                                        .addComponent(txt_kullanici_adi2)
                                        .addComponent(ptxt_sifre2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                    .addComponent(txt_email2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_hazir2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_kayit_ol2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_beyazBekleniyor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel11)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_email2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txt_kullanici_adi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ptxt_sifre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chcbx_sifregoster2)
                .addGap(28, 28, 28)
                .addComponent(btn_hazir2)
                .addGap(18, 18, 18)
                .addComponent(btn_kayit_ol2)
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_beyazBekleniyor)
                    .addComponent(jLabel8))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kullanici_adi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kullanici_adi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kullanici_adi1ActionPerformed

    private void btn_hazir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hazir1ActionPerformed
        //siyah oyuncunun hazir olup olmamasi
        kullanici1.email = txt_email1.getText();
        kullanici1.kullanici_Adi = txt_kullanici_adi1.getText();
        kullanici1.parola = new String(ptxt_sifre1.getPassword());

        boolean isLogin = AliEnesGurelData.Login(kullanici1.email, kullanici1.kullanici_Adi, kullanici1.parola);
        if (isLogin) {
            if (kullanici1.kullanici_Adi.equals(txt_kullanici_adi2.getText()) && kullanici1.parola.equals(new String(ptxt_sifre2.getPassword())) && !txt_kullanici_adi1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "kullanici adiniz beyaz oyuncu ile ayni olamaz!");
            } else {
                lbl_siyahBekleniyor.setText("HAZIR");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Böyle bir kullanıcı bulunmamaktadır! İlk önce kayıt olmanız gerekmektedir.");
        }
        if (isLogin && lbl_beyazBekleniyor.getText().equals("HAZIR") && lbl_siyahBekleniyor.getText().equals("HAZIR")) {
            AliEnesGurelFrm_GameScene oyun_ekrani = new AliEnesGurelFrm_GameScene();
            oyun_ekrani.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_hazir1ActionPerformed

    private void chcbx_sifregoster1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcbx_sifregoster1ActionPerformed
        if (chcbx_sifregoster1.isSelected()) {//sifre gosterme1
            ptxt_sifre1.setEchoChar((char) 0);
        } else {
            ptxt_sifre1.setEchoChar('*');
        }
    }//GEN-LAST:event_chcbx_sifregoster1ActionPerformed

    private void chcbx_sifregoster2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcbx_sifregoster2ActionPerformed
        if (chcbx_sifregoster2.isSelected()) {//sifre gosterme2
            ptxt_sifre2.setEchoChar((char) 0);
        } else {
            ptxt_sifre2.setEchoChar('*');
        }
    }//GEN-LAST:event_chcbx_sifregoster2ActionPerformed

    private void btn_kayit_ol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayit_ol1ActionPerformed
        this.setVisible(false);//1. oyuncu icin kayit ekrani gelir
        AliEnesGurelRegister register = new AliEnesGurelRegister(this);
        register.setVisible(true);
    }//GEN-LAST:event_btn_kayit_ol1ActionPerformed

    private void btn_kayit_ol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayit_ol2ActionPerformed
        this.setVisible(false);//2. oyuncu icin kayit ekrani
        AliEnesGurelRegister register = new AliEnesGurelRegister(this);
        register.setVisible(true);
    }//GEN-LAST:event_btn_kayit_ol2ActionPerformed

    private void btn_hazir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hazir2ActionPerformed
        kullanici2.email = txt_email2.getText();//beyaz oyuncunun hazir butonunun olaylari
        kullanici2.kullanici_Adi = txt_kullanici_adi2.getText();
        kullanici2.parola = new String(ptxt_sifre2.getPassword());

        boolean isLogin = AliEnesGurelData.Login(kullanici2.email, kullanici2.kullanici_Adi, kullanici2.parola);
        if (isLogin) {
            if (kullanici2.kullanici_Adi.equals(txt_kullanici_adi1.getText()) && kullanici2.parola.equals(new String(ptxt_sifre1.getPassword())) && !txt_kullanici_adi2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "kullanici adiniz siyah oyuncu ile ayni olamaz!");
            } else {
                lbl_beyazBekleniyor.setText("HAZIR");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Böyle bir kullanıcı bulunmamaktadır! İlk önce kayıt olmanız gerekmektedir.");
        }
        if (isLogin && lbl_beyazBekleniyor.getText().equals("HAZIR") && lbl_siyahBekleniyor.getText().equals("HAZIR")) {
            AliEnesGurelFrm_GameScene oyun_ekrani = new AliEnesGurelFrm_GameScene();
            oyun_ekrani.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_hazir2ActionPerformed

    private void txt_email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email1ActionPerformed

    private void txt_kullanici_adi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kullanici_adi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kullanici_adi2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hazir1;
    private javax.swing.JButton btn_hazir2;
    private javax.swing.JButton btn_kayit_ol1;
    private javax.swing.JButton btn_kayit_ol2;
    private javax.swing.JCheckBox chcbx_sifregoster1;
    private javax.swing.JCheckBox chcbx_sifregoster2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_beyazBekleniyor;
    private javax.swing.JLabel lbl_siyahBekleniyor;
    private javax.swing.JPasswordField ptxt_sifre1;
    private javax.swing.JPasswordField ptxt_sifre2;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JTextField txt_email2;
    private javax.swing.JTextField txt_kullanici_adi1;
    private javax.swing.JTextField txt_kullanici_adi2;
    // End of variables declaration//GEN-END:variables
}
