/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.bp2project1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alien
 */
public class AliEnesGurelSkorTablosu extends javax.swing.JFrame {

    AliEnesGurelLogin login = new AliEnesGurelLogin();
    public AliEnesGurelKullanici kullanici;
    public String skoru;

    /**
     * Creates new form SkorTablosu
     */
    public AliEnesGurelSkorTablosu() {
        setTitle("SKOR TABLOSU");
        initComponents();
    }

    @Override
    public String toString() {//txt dosyasina skorlari bu sekil yazdirir
        String values = "";
        values += this.kullanici.email + " & ";
        values += this.kullanici.kullanici_Adi + " & ";
        values += this.kullanici.parola + " & ";
        values += this.skoru + "\n";
        return values;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_skorTablosu = new javax.swing.JTable();
        btn_sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 25));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SKOR TABLOSU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 333, 0, 321);
        jPanel1.add(jLabel1, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbl_skorTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KAZANAN OYUNCU", "SKORU", "RAKIP PUANI", "HAMLE SAYISI"
            }
        ));
        tbl_skorTablosu.setMaximumSize(new java.awt.Dimension(800, 400));
        tbl_skorTablosu.setMinimumSize(new java.awt.Dimension(800, 400));
        tbl_skorTablosu.setPreferredSize(new java.awt.Dimension(800, 400));
        jScrollPane1.setViewportView(tbl_skorTablosu);

        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        DefaultTableModel scoreTable = (DefaultTableModel) tbl_skorTablosu.getModel();//sil butonuna basilmasi
        int secilen = tbl_skorTablosu.getSelectedRow();
        String ad = scoreTable.getValueAt(secilen, 0).toString();
        if (ad.equals(login.getKullanici1().kullanici_Adi)) {
            kontrolluSil(login.getKullanici1());
        } else if (ad.equals(login.getKullanici2().kullanici_Adi)) {
            kontrolluSil(login.getKullanici2());
        } else {
            //berabere durumunda bilgi isteme.
            scoreTable.removeRow(secilen);
            txtdenSkorSil(secilen);
        }
    }//GEN-LAST:event_btn_silActionPerformed

    public void kontrolluSil(AliEnesGurelKullanici kullanici) {
        boolean sildiMi = false;//bazi kontroller sonucu tablodan skor siler
        DefaultTableModel scoreTable = (DefaultTableModel) tbl_skorTablosu.getModel();
        int secilen = tbl_skorTablosu.getSelectedRow();
        String mailOnayla = JOptionPane.showInputDialog(rootPane, "Lutfen e-mail adresinizi giriniz.", JOptionPane.INFORMATION_MESSAGE);
        if (mailOnayla.compareTo(kullanici.email) == 0) {
            String parolaOnayla = JOptionPane.showInputDialog(rootPane, "Lutfen parolanizi giriniz.", JOptionPane.INFORMATION_MESSAGE);
            if (parolaOnayla.compareTo(kullanici.parola) == 0) {
                scoreTable.removeRow(secilen);
                sildiMi = true;
            } else {
                JOptionPane.showMessageDialog(rootPane, "hatali parola");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "hatali e-mail adresi");
        }
        if (kullanici.email.equals("OYUN")) {
            sildiMi = true;
        }
        if (sildiMi == true) {
            //burada txt den silmeliyim.
            txtdenSkorSil(secilen);
        }
    }

    public void txtdenSkorSil(int secilen) {
        try {
            AliEnesGurelData.skorListesi.remove(secilen);
            AliEnesGurelData.DosyayaSkorYazdirma();
            JOptionPane.showMessageDialog(null, "Skor basariyla silinmistir.");
        } catch (IOException ex) {
            Logger.getLogger(AliEnesGurelSkorTablosu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JButton getBtn_sil() {
        return btn_sil;
    }

    public void setBtn_sil(JButton btn_sil) {
        this.btn_sil = btn_sil;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbl_skorTablosu() {
        return tbl_skorTablosu;
    }

    public void setTbl_skorTablosu(JTable tbl_skorTablosu) {
        this.tbl_skorTablosu = tbl_skorTablosu;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_skorTablosu;
    // End of variables declaration//GEN-END:variables
}
